[package]
name = "steven"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]

[profile.dev]
# Steven runs horrendously slow with no optimizations, and often freezes.
# However, building with full -O3 optimizations takes too long for a debug build.
# Use an -O1 optimization level strikes a good compromise between build and program performance.
opt-level = 1

[dependencies]
sha-1 = "0.8.0"
sdl2 = "0.31.0"
byteorder = "1.2.6"
reqwest = "0.9.4"
serde = "1.0.79"
serde_json = "1.0.31"
flate2 = "1.0.2"
zip = "0.4.2"
image = "0.20.0"
rand = "0.5.5"
hex = "0.3.2"
base64 = "0.9.3"
log = { version = "0.4.5", features = ["std"] }
cgmath = "0.16.1"
lazy_static = "1.1.0"
collision = "0.18.0"
openssl = "0.10.15"
# clippy = "*"

[dependencies.steven_gl]
path = "./gl"
version = "0"

[dependencies.steven_resources]
path = "./resources"
version = "0"

[dependencies.steven_blocks]
path = "./blocks"
version = "0"

[dependencies.steven_shared]
path = "./shared"
version = "0"
