
use std::sync::{Arc, RwLock};
use std::collections::HashMap;
use std::hash::BuildHasherDefault;

use sdl2_mixer::{self, LoaderRWops};
use sdl2::rwops::RWops;
use serde_json;
use resources;
use types::hash::FNVHash;

pub struct Manager {
    resource_manager: Arc<RwLock<resources::Manager>>,
    version: usize,
    sound_buffers: HashMap<String, Vec<sdl2_mixer::Chunk>, BuildHasherDefault<FNVHash>>,
    sound_names: HashMap<String, Vec<String>, BuildHasherDefault<FNVHash>>,
}

impl Manager {
    pub fn new(resource_manager: Arc<RwLock<resources::Manager>>) -> Manager {
        Manager {
            resource_manager: resource_manager,
            version: 0xFFFFFF,
            sound_buffers: HashMap::default(),
            sound_names: HashMap::default(),
        }
    }

    pub fn tick(&mut self, version: usize) {
        if self.version != version {
            self.version = version;
            self.reload_sounds();
        }
    }

    fn reload_sounds(&mut self) {
        self.sound_buffers.clear();
        self.sound_names.clear();
        if let Some(sound_list) = self.resource_manager.read().unwrap().open("minecraft", "sounds.json") {
            let sounds: serde_json::Value = serde_json::from_reader(sound_list).unwrap();
            for (k, v) in sounds.as_object().unwrap() {
                let slist = v.find("sounds").and_then(|v| v.as_array()).unwrap();
                let mut sounds = vec![];
                for v in slist {
                    if let serde_json::Value::String(ref s) = *v {
                        sounds.push(s.clone());
                    } else {
                        info!("Skipping unsupported sound type: {:?}", v);
                    }
                }
                self.sound_names.insert(k.to_owned(), sounds);
            }
        } else {
            error!("No sounds.json found");
        }
    }

    pub fn play_sound(&mut self, name: &str, volume: f64, pitch: f64) {
        use rand::{self, Rng};
        let name = if name.starts_with("minecraft:") {
            &name["minecraft:".len()..]
        } else {
            name
        };
        if !self.sound_buffers.contains_key(name) {
            let resources = self.resource_manager.read().unwrap();
            if let Some(slist) = self.sound_names.get(name) {
                let mut sounds = vec![];
                for s in slist {
                    if let Some(mut file) = resources.open("minecraft", &format!("sounds/{}.ogg", s)) {
                        let mut buf = vec![];
                        file.read_to_end(&mut buf).unwrap();
                        let data = RWops::from_bytes(&buf).unwrap();
                        sounds.push(data.load_wav().unwrap());
                    } else {
                        warn!("Missing sound file: {}", s);
                    }
                }
                self.sound_buffers.insert(name.to_owned(), sounds);
            } else {
                warn!("Missing sound: {}", name);
                return;
            }
        }
        let mut rng = rand::thread_rng();
        let sounds = &self.sound_buffers[name];
        if let Some(snd) = rng.choose(sounds) {
            let snd = match sdl2_mixer::Channel::all().play(snd, 0) {
                Ok(val) => val,
                Err(_) => return, // Most likely ran out of channels
            };
            snd.set_volume((volume * 128.0) as isize);
            let _ = pitch; // TODO :(
        }
    }

    pub fn play_sound_by_id(&mut self, id: i32, volume: f64, pitch: f64) {
        if let Some(name) = network::BY_ID.get(id as usize) {
            self.play_sound(name, volume, pitch);
        }
    }
}

pub mod network {
    pub const BY_ID: &'static [&'static str] = &[
        "minecraft:ambient.cave",
        "minecraft:block.anvil.break",
        "minecraft:block.anvil.destroy",
        "minecraft:block.anvil.fall",
        "minecraft:block.anvil.hit",
        "minecraft:block.anvil.land",
        "minecraft:block.anvil.place",
        "minecraft:block.anvil.step",
        "minecraft:block.anvil.use",
        "minecraft:block.brewing_stand.brew",
        "minecraft:block.chest.close",
        "minecraft:block.chest.locked",
        "minecraft:block.chest.open",
        "minecraft:block.chorus_flower.death",
        "minecraft:block.chorus_flower.grow",
        "minecraft:block.cloth.break",
        "minecraft:block.cloth.fall",
        "minecraft:block.cloth.hit",
        "minecraft:block.cloth.place",
        "minecraft:block.cloth.step",
        "minecraft:block.comparator.click",
        "minecraft:block.dispenser.dispense",
        "minecraft:block.dispenser.fail",
        "minecraft:block.dispenser.launch",
        "minecraft:block.end_gateway.spawn",
        "minecraft:block.enderchest.close",
        "minecraft:block.enderchest.open",
        "minecraft:block.fence_gate.close",
        "minecraft:block.fence_gate.open",
        "minecraft:block.fire.ambient",
        "minecraft:block.fire.extinguish",
        "minecraft:block.furnace.fire_crackle",
        "minecraft:block.glass.break",
        "minecraft:block.glass.fall",
        "minecraft:block.glass.hit",
        "minecraft:block.glass.place",
        "minecraft:block.glass.step",
        "minecraft:block.grass.break",
        "minecraft:block.grass.fall",
        "minecraft:block.grass.hit",
        "minecraft:block.grass.place",
        "minecraft:block.grass.step",
        "minecraft:block.gravel.break",
        "minecraft:block.gravel.fall",
        "minecraft:block.gravel.hit",
        "minecraft:block.gravel.place",
        "minecraft:block.gravel.step",
        "minecraft:block.iron_door.close",
        "minecraft:block.iron_door.open",
        "minecraft:block.iron_trapdoor.close",
        "minecraft:block.iron_trapdoor.open",
        "minecraft:block.ladder.break",
        "minecraft:block.ladder.fall",
        "minecraft:block.ladder.hit",
        "minecraft:block.ladder.place",
        "minecraft:block.ladder.step",
        "minecraft:block.lava.ambient",
        "minecraft:block.lava.extinguish",
        "minecraft:block.lava.pop",
        "minecraft:block.lever.click",
        "minecraft:block.metal.break",
        "minecraft:block.metal.fall",
        "minecraft:block.metal.hit",
        "minecraft:block.metal.place",
        "minecraft:block.metal.step",
        "minecraft:block.metal_pressureplate.click_off",
        "minecraft:block.metal_pressureplate.click_on",
        "minecraft:block.note.basedrum",
        "minecraft:block.note.bass",
        "minecraft:block.note.harp",
        "minecraft:block.note.hat",
        "minecraft:block.note.pling",
        "minecraft:block.note.snare",
        "minecraft:block.piston.contract",
        "minecraft:block.piston.extend",
        "minecraft:block.portal.ambient",
        "minecraft:block.portal.travel",
        "minecraft:block.portal.trigger",
        "minecraft:block.redstone_torch.burnout",
        "minecraft:block.sand.break",
        "minecraft:block.sand.fall",
        "minecraft:block.sand.hit",
        "minecraft:block.sand.place",
        "minecraft:block.sand.step",
        "minecraft:block.slime.break",
        "minecraft:block.slime.fall",
        "minecraft:block.slime.hit",
        "minecraft:block.slime.place",
        "minecraft:block.slime.step",
        "minecraft:block.snow.break",
        "minecraft:block.snow.fall",
        "minecraft:block.snow.hit",
        "minecraft:block.snow.place",
        "minecraft:block.snow.step",
        "minecraft:block.stone.break",
        "minecraft:block.stone.fall",
        "minecraft:block.stone.hit",
        "minecraft:block.stone.place",
        "minecraft:block.stone.step",
        "minecraft:block.stone_button.click_off",
        "minecraft:block.stone_button.click_on",
        "minecraft:block.stone_pressureplate.click_off",
        "minecraft:block.stone_pressureplate.click_on",
        "minecraft:block.tripwire.attach",
        "minecraft:block.tripwire.click_off",
        "minecraft:block.tripwire.click_on",
        "minecraft:block.tripwire.detach",
        "minecraft:block.water.ambient",
        "minecraft:block.waterlily.place",
        "minecraft:block.wood.break",
        "minecraft:block.wood.fall",
        "minecraft:block.wood.hit",
        "minecraft:block.wood.place",
        "minecraft:block.wood.step",
        "minecraft:block.wood_button.click_off",
        "minecraft:block.wood_button.click_on",
        "minecraft:block.wood_pressureplate.click_off",
        "minecraft:block.wood_pressureplate.click_on",
        "minecraft:block.wooden_door.close",
        "minecraft:block.wooden_door.open",
        "minecraft:block.wooden_trapdoor.close",
        "minecraft:block.wooden_trapdoor.open",
        "minecraft:enchant.thorns.hit",
        "minecraft:entity.armorstand.break",
        "minecraft:entity.armorstand.fall",
        "minecraft:entity.armorstand.hit",
        "minecraft:entity.armorstand.place",
        "minecraft:entity.arrow.hit",
        "minecraft:entity.arrow.hit_player",
        "minecraft:entity.arrow.shoot",
        "minecraft:entity.bat.ambient",
        "minecraft:entity.bat.death",
        "minecraft:entity.bat.hurt",
        "minecraft:entity.bat.loop",
        "minecraft:entity.bat.takeoff",
        "minecraft:entity.blaze.ambient",
        "minecraft:entity.blaze.burn",
        "minecraft:entity.blaze.death",
        "minecraft:entity.blaze.hurt",
        "minecraft:entity.blaze.shoot",
        "minecraft:entity.bobber.splash",
        "minecraft:entity.bobber.throw",
        "minecraft:entity.cat.ambient",
        "minecraft:entity.cat.death",
        "minecraft:entity.cat.hiss",
        "minecraft:entity.cat.hurt",
        "minecraft:entity.cat.purr",
        "minecraft:entity.cat.purreow",
        "minecraft:entity.chicken.ambient",
        "minecraft:entity.chicken.death",
        "minecraft:entity.chicken.egg",
        "minecraft:entity.chicken.hurt",
        "minecraft:entity.chicken.step",
        "minecraft:entity.cow.ambient",
        "minecraft:entity.cow.death",
        "minecraft:entity.cow.hurt",
        "minecraft:entity.cow.milk",
        "minecraft:entity.cow.step",
        "minecraft:entity.creeper.death",
        "minecraft:entity.creeper.hurt",
        "minecraft:entity.creeper.primed",
        "minecraft:entity.donkey.ambient",
        "minecraft:entity.donkey.angry",
        "minecraft:entity.donkey.chest",
        "minecraft:entity.donkey.death",
        "minecraft:entity.donkey.hurt",
        "minecraft:entity.egg.throw",
        "minecraft:entity.elder_guardian.ambient",
        "minecraft:entity.elder_guardian.ambient_land",
        "minecraft:entity.elder_guardian.curse",
        "minecraft:entity.elder_guardian.death",
        "minecraft:entity.elder_guardian.death_land",
        "minecraft:entity.elder_guardian.hurt",
        "minecraft:entity.elder_guardian.hurt_land",
        "minecraft:entity.enderdragon.ambient",
        "minecraft:entity.enderdragon.death",
        "minecraft:entity.enderdragon.flap",
        "minecraft:entity.enderdragon.growl",
        "minecraft:entity.enderdragon.hurt",
        "minecraft:entity.enderdragon.shoot",
        "minecraft:entity.enderdragon_fireball.explode",
        "minecraft:entity.endereye.launch",
        "minecraft:entity.endermen.ambient",
        "minecraft:entity.endermen.death",
        "minecraft:entity.endermen.hurt",
        "minecraft:entity.endermen.scream",
        "minecraft:entity.endermen.stare",
        "minecraft:entity.endermen.teleport",
        "minecraft:entity.endermite.ambient",
        "minecraft:entity.endermite.death",
        "minecraft:entity.endermite.hurt",
        "minecraft:entity.endermite.step",
        "minecraft:entity.enderpearl.throw",
        "minecraft:entity.experience_bottle.throw",
        "minecraft:entity.experience_orb.pickup",
        "minecraft:entity.experience_orb.touch",
        "minecraft:entity.firework.blast",
        "minecraft:entity.firework.blast_far",
        "minecraft:entity.firework.large_blast",
        "minecraft:entity.firework.large_blast_far",
        "minecraft:entity.firework.launch",
        "minecraft:entity.firework.shoot",
        "minecraft:entity.firework.twinkle",
        "minecraft:entity.firework.twinkle_far",
        "minecraft:entity.generic.big_fall",
        "minecraft:entity.generic.burn",
        "minecraft:entity.generic.death",
        "minecraft:entity.generic.drink",
        "minecraft:entity.generic.eat",
        "minecraft:entity.generic.explode",
        "minecraft:entity.generic.extinguish_fire",
        "minecraft:entity.generic.hurt",
        "minecraft:entity.generic.small_fall",
        "minecraft:entity.generic.splash",
        "minecraft:entity.generic.swim",
        "minecraft:entity.ghast.ambient",
        "minecraft:entity.ghast.death",
        "minecraft:entity.ghast.hurt",
        "minecraft:entity.ghast.scream",
        "minecraft:entity.ghast.shoot",
        "minecraft:entity.ghast.warn",
        "minecraft:entity.guardian.ambient",
        "minecraft:entity.guardian.ambient_land",
        "minecraft:entity.guardian.attack",
        "minecraft:entity.guardian.death",
        "minecraft:entity.guardian.death_land",
        "minecraft:entity.guardian.flop",
        "minecraft:entity.guardian.hurt",
        "minecraft:entity.guardian.hurt_land",
        "minecraft:entity.horse.ambient",
        "minecraft:entity.horse.angry",
        "minecraft:entity.horse.armor",
        "minecraft:entity.horse.breathe",
        "minecraft:entity.horse.death",
        "minecraft:entity.horse.eat",
        "minecraft:entity.horse.gallop",
        "minecraft:entity.horse.hurt",
        "minecraft:entity.horse.jump",
        "minecraft:entity.horse.land",
        "minecraft:entity.horse.saddle",
        "minecraft:entity.horse.step",
        "minecraft:entity.horse.step_wood",
        "minecraft:entity.hostile.big_fall",
        "minecraft:entity.hostile.death",
        "minecraft:entity.hostile.hurt",
        "minecraft:entity.hostile.small_fall",
        "minecraft:entity.hostile.splash",
        "minecraft:entity.hostile.swim",
        "minecraft:entity.irongolem.attack",
        "minecraft:entity.irongolem.death",
        "minecraft:entity.irongolem.hurt",
        "minecraft:entity.irongolem.step",
        "minecraft:entity.item.break",
        "minecraft:entity.item.pickup",
        "minecraft:entity.itemframe.add_item",
        "minecraft:entity.itemframe.break",
        "minecraft:entity.itemframe.place",
        "minecraft:entity.itemframe.remove_item",
        "minecraft:entity.itemframe.rotate_item",
        "minecraft:entity.leashknot.break",
        "minecraft:entity.leashknot.place",
        "minecraft:entity.lightning.impact",
        "minecraft:entity.lightning.thunder",
        "minecraft:entity.lingeringpotion.throw",
        "minecraft:entity.magmacube.death",
        "minecraft:entity.magmacube.hurt",
        "minecraft:entity.magmacube.jump",
        "minecraft:entity.magmacube.squish",
        "minecraft:entity.minecart.inside",
        "minecraft:entity.minecart.riding",
        "minecraft:entity.mooshroom.shear",
        "minecraft:entity.mule.ambient",
        "minecraft:entity.mule.death",
        "minecraft:entity.mule.hurt",
        "minecraft:entity.painting.break",
        "minecraft:entity.painting.place",
        "minecraft:entity.pig.ambient",
        "minecraft:entity.pig.death",
        "minecraft:entity.pig.hurt",
        "minecraft:entity.pig.saddle",
        "minecraft:entity.pig.step",
        "minecraft:entity.player.attack.crit",
        "minecraft:entity.player.attack.knockback",
        "minecraft:entity.player.attack.nodamage",
        "minecraft:entity.player.attack.strong",
        "minecraft:entity.player.attack.sweep",
        "minecraft:entity.player.attack.weak",
        "minecraft:entity.player.big_fall",
        "minecraft:entity.player.breath",
        "minecraft:entity.player.burp",
        "minecraft:entity.player.death",
        "minecraft:entity.player.hurt",
        "minecraft:entity.player.levelup",
        "minecraft:entity.player.small_fall",
        "minecraft:entity.player.splash",
        "minecraft:entity.player.swim",
        "minecraft:entity.rabbit.ambient",
        "minecraft:entity.rabbit.attack",
        "minecraft:entity.rabbit.death",
        "minecraft:entity.rabbit.hurt",
        "minecraft:entity.rabbit.jump",
        "minecraft:entity.sheep.ambient",
        "minecraft:entity.sheep.death",
        "minecraft:entity.sheep.hurt",
        "minecraft:entity.sheep.shear",
        "minecraft:entity.sheep.step",
        "minecraft:entity.shulker.ambient",
        "minecraft:entity.shulker.close",
        "minecraft:entity.shulker.death",
        "minecraft:entity.shulker.hurt",
        "minecraft:entity.shulker.hurt_closed",
        "minecraft:entity.shulker.open",
        "minecraft:entity.shulker.shoot",
        "minecraft:entity.shulker.teleport",
        "minecraft:entity.shulker_bullet.hit",
        "minecraft:entity.shulker_bullet.hurt",
        "minecraft:entity.silverfish.ambient",
        "minecraft:entity.silverfish.death",
        "minecraft:entity.silverfish.hurt",
        "minecraft:entity.silverfish.step",
        "minecraft:entity.skeleton.ambient",
        "minecraft:entity.skeleton.death",
        "minecraft:entity.skeleton.hurt",
        "minecraft:entity.skeleton.shoot",
        "minecraft:entity.skeleton.step",
        "minecraft:entity.skeleton_horse.ambient",
        "minecraft:entity.skeleton_horse.death",
        "minecraft:entity.skeleton_horse.hurt",
        "minecraft:entity.slime.attack",
        "minecraft:entity.slime.death",
        "minecraft:entity.slime.hurt",
        "minecraft:entity.slime.jump",
        "minecraft:entity.slime.squish",
        "minecraft:entity.small_magmacube.death",
        "minecraft:entity.small_magmacube.hurt",
        "minecraft:entity.small_magmacube.squish",
        "minecraft:entity.small_slime.death",
        "minecraft:entity.small_slime.hurt",
        "minecraft:entity.small_slime.jump",
        "minecraft:entity.small_slime.squish",
        "minecraft:entity.snowball.throw",
        "minecraft:entity.snowman.ambient",
        "minecraft:entity.snowman.death",
        "minecraft:entity.snowman.hurt",
        "minecraft:entity.snowman.shoot",
        "minecraft:entity.spider.ambient",
        "minecraft:entity.spider.death",
        "minecraft:entity.spider.hurt",
        "minecraft:entity.spider.step",
        "minecraft:entity.splash_potion.break",
        "minecraft:entity.splash_potion.throw",
        "minecraft:entity.squid.ambient",
        "minecraft:entity.squid.death",
        "minecraft:entity.squid.hurt",
        "minecraft:entity.tnt.primed",
        "minecraft:entity.villager.ambient",
        "minecraft:entity.villager.death",
        "minecraft:entity.villager.hurt",
        "minecraft:entity.villager.no",
        "minecraft:entity.villager.trading",
        "minecraft:entity.villager.yes",
        "minecraft:entity.witch.ambient",
        "minecraft:entity.witch.death",
        "minecraft:entity.witch.drink",
        "minecraft:entity.witch.hurt",
        "minecraft:entity.witch.throw",
        "minecraft:entity.wither.ambient",
        "minecraft:entity.wither.break_block",
        "minecraft:entity.wither.death",
        "minecraft:entity.wither.hurt",
        "minecraft:entity.wither.shoot",
        "minecraft:entity.wither.spawn",
        "minecraft:entity.wolf.ambient",
        "minecraft:entity.wolf.death",
        "minecraft:entity.wolf.growl",
        "minecraft:entity.wolf.howl",
        "minecraft:entity.wolf.hurt",
        "minecraft:entity.wolf.pant",
        "minecraft:entity.wolf.shake",
        "minecraft:entity.wolf.step",
        "minecraft:entity.wolf.whine",
        "minecraft:entity.zombie.ambient",
        "minecraft:entity.zombie.attack_door_wood",
        "minecraft:entity.zombie.attack_iron_door",
        "minecraft:entity.zombie.break_door_wood",
        "minecraft:entity.zombie.death",
        "minecraft:entity.zombie.hurt",
        "minecraft:entity.zombie.infect",
        "minecraft:entity.zombie.step",
        "minecraft:entity.zombie_horse.ambient",
        "minecraft:entity.zombie_horse.death",
        "minecraft:entity.zombie_horse.hurt",
        "minecraft:entity.zombie_pig.ambient",
        "minecraft:entity.zombie_pig.angry",
        "minecraft:entity.zombie_pig.death",
        "minecraft:entity.zombie_pig.hurt",
        "minecraft:entity.zombie_villager.ambient",
        "minecraft:entity.zombie_villager.converted",
        "minecraft:entity.zombie_villager.cure",
        "minecraft:entity.zombie_villager.death",
        "minecraft:entity.zombie_villager.hurt",
        "minecraft:entity.zombie_villager.step",
        "minecraft:item.armor.equip_chain",
        "minecraft:item.armor.equip_diamond",
        "minecraft:item.armor.equip_generic",
        "minecraft:item.armor.equip_gold",
        "minecraft:item.armor.equip_iron",
        "minecraft:item.armor.equip_leather",
        "minecraft:item.bottle.fill",
        "minecraft:item.bottle.fill_dragonbreath",
        "minecraft:item.bucket.empty",
        "minecraft:item.bucket.empty_lava",
        "minecraft:item.bucket.fill",
        "minecraft:item.bucket.fill_lava",
        "minecraft:item.chorus_fruit.teleport",
        "minecraft:item.elytra.flying",
        "minecraft:item.firecharge.use",
        "minecraft:item.flintandsteel.use",
        "minecraft:item.hoe.till",
        "minecraft:item.shield.block",
        "minecraft:item.shield.break",
        "minecraft:item.shovel.flatten",
        "minecraft:music.creative",
        "minecraft:music.credits",
        "minecraft:music.dragon",
        "minecraft:music.end",
        "minecraft:music.game",
        "minecraft:music.menu",
        "minecraft:music.nether",
        "minecraft:record.11",
        "minecraft:record.13",
        "minecraft:record.blocks",
        "minecraft:record.cat",
        "minecraft:record.chirp",
        "minecraft:record.far",
        "minecraft:record.mall",
        "minecraft:record.mellohi",
        "minecraft:record.stal",
        "minecraft:record.strad",
        "minecraft:record.wait",
        "minecraft:record.ward",
        "minecraft:ui.button.click",
        "minecraft:weather.rain",
        "minecraft:weather.rain.above",
    ];
}
